name: Terraform Plan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log Job Start
        run: echo Running Teraform Check

      - name: Rewrite Terraform configuration files to a canonical format and style
        run: terraform fmt

      - name: Log Job Completion
        run: echo Completed Teraform Check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: arn:aws:iam::058264092396:role/GithubActionsRole-DSS
              aws-region: us-east-1

      - name: Log Job Start
        run: echo Running Teraform Plan

      - name: Initialize Terraform
        run: terraform init

      - name: Create an execution plan, which lets you preview the changes that Terraform plans to make to your infrastructure.
        run: terraform plan

      - name: Log Job Completion
        run: echo Completed Teraform Plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: arn:aws:iam::058264092396:role/GithubActionsRole-DSS
              aws-region: us-east-1

      - name: Log Job Start
        run: echo Running Teraform Apply

      - name: Initialize Terraform
        run: terraform init

      - name: Executes the actions proposed in a Terraform plan
        run: terraform apply -auto-approve

      - name: Log Job Completion
        run: echo Completed Teraform Apply
