# This is a basic workflow to help you get started with Actions

name: Terraform Plan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-check:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Log Job Start
        run: echo Running Teraform Check

      - name: Rewrite Terraform configuration files to a canonical format and style
        run: terraform fmt

      - name: Log Job Completion
        run: echo Completed Teraform Check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - uses: actions/checkout@v4

      - name: Log Job Start
        run: echo Running Teraform Plan

      - name: Initialize Terraform
        run: terraform init

      - name: Create an execution plan, which lets you preview the changes that Terraform plans to make to your infrastructure.
        run: terraform plan

      - name: Log Job Completion
        run: echo Completed Teraform Plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v4

      - name: Log Job Start
        run: echo Running Teraform Apply

      - name: Initialize Terraform
        run: terraform init

      - name: Executes the actions proposed in a Terraform plan
        run: terraform apply

      - name: Log Job Completion
        run: echo Completed Teraform Apply
